baseURL = "https://alottodo.github.io/ModernWorkplaceShenanigans/"
languageCode = "en-us"
title = "Modern Workplace Shenanigans"
theme = "PaperMod"

[pagination]
  pagerSize = 10
  
[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.label]
    text = "Modern Workplace Shenanigans"
    icon = "/ModernWorkplaceShenanigans/images/logo-mws.png"
    iconHeight = 70

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
